Tblog/blueprints/admin.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_required, current_user
from Tblog.extensions import db
from Tblog.models import Admin, Article
from Tblog.utils import redirect_back
from Tblog.forms import SettingForm, SignInForm

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/articles/show', methods=['GET', 'POST'])
@login_required
def switch_show_state():
    aid = request.form.get('aid')

    article = Article.query.get(aid)
    article.show = not article.show
    db.session.add(article)
    db.session.commit()
    return redirect_back()


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about

    return render_template('admin/settings.html', form=form)


@admin_bp.route('/reset_password', methods=['GET', 'POST'])
@login_required
def reset_password():
    form = SignInForm()
    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        db.session.commit()
        flash('Password  updated.', 'success')
        return redirect(url_for('blog.index'))
    return render_template('admin/reset_password.html', form=form)


@admin_bp.route('/token', methods=['GET', 'POST'])
@login_required
def get_auth_token():
    admin = Admin.query.first()
    if request.form.get('reset'):
        admin.set_api_key()
        flash("Reset token success!", "info")
    token = admin.api_key
    return render_template('admin/token.html', token=token)


@admin_bp.route('/mange', methods=['GET', 'POST'])
@login_required
def mange():
    settings_form = SettingForm()
    reset_password_form = SignInForm()
    if settings_form.validate_on_submit():
        return settings()
    if reset_password_form.validate_on_submit():
        return reset_password()
    admin = Admin.query.first()
    if request.form.get('reset'):
        admin.set_api_key()
        flash("Reset token success!", "info")
    token = admin.api_key

    settings_form.name.data = current_user.name
    settings_form.blog_title.data = current_user.blog_title
    settings_form.blog_sub_title.data = current_user.blog_sub_title
    settings_form.about.data = current_user.about

    return render_template('admin/mange.html',
                           token=token,
                           settings_form=settings_form,
                           reset_password_form=reset_password_form)

Tblog/blueprints/auth.py
from flask import (Blueprint, flash, redirect, session, json, render_template,
                   url_for)
from flask_login import current_user, login_required, login_user, logout_user
from authlib.common.errors import AuthlibBaseError
from Tblog.extensions import oauth, db
from Tblog.forms import LoginForm
from Tblog.models import Admin
from Tblog.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        session['username'] = current_user.username
        return redirect(url_for('blog.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        if not Admin.query.first():
            flash('Please Login Use Github', 'info')
            return render_template('auth/login.html', form=form)

        admin = Admin.query.filter_by(username=username).first()
        if admin:
            if admin.verify_password(password):
                login_user(admin, remember)
                session['username'] = username
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            flash('Invalid username or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/oauth/github')
def login_github():
    github = oauth.create_client('github')
    return github.authorize_redirect(url_for('auth.authorized',
                                             _external=True))


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('github_token', None)
    return redirect_back()


@auth_bp.route('/login/authorized')
def authorized():
    try:
        oauth.github.authorize_access_token()
    except AuthlibBaseError as e:
        flash(str(e), 'warning')
        return redirect(url_for('auth.login'))
    resp = oauth.github.get('user/emails')

    username = oauth.github.get('user').json().get('login')

    emails = json.loads(resp.text)
    primary_email = [email['email'] for email in emails if email['primary']]
    if not primary_email:
        flash("Plz check your primary email is right")
        return redirect(url_for('auth.login'))
    primary_email = primary_email[0]
    if Admin.query.first() is None:
        admin = Admin(username=username, email=primary_email)
        admin.set_api_key()
        admin.set_password(admin.api_key)
        db.session.add(admin)
        db.session.commit()
        login_user(admin, remember=True)
        return redirect(url_for('admin.settings'))

    admin = Admin.query.filter_by(email=primary_email).first()
    session['username'] = username
    if admin:
        login_user(admin, remember=True)
        flash("Welcome come back", 'info')
        return redirect_back()
    else:
        flash("Welcome to tblog {username}".format(username=username), "info")
        return redirect_back()

Tblog/blueprints/blog.py
from flask import session, render_template, Blueprint, abort
from flask_login import current_user
from sqlalchemy import or_
from Tblog.models import Article, Category, Admin
import markdown
import pygments
from pygments import highlight
from pygments.lexers import get_lexer_by_name, guess_lexer
from pygments.formatters import HtmlFormatter
import re
# import markdown
blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/articles')
@blog_bp.route('/')
def index():
    username = session.get('username', 'no_exist_user')
    if current_user.is_authenticated:
        posts = Article.query.order_by(Article.timestamp.desc())
    else:

        posts = Article.query.filter(
            or_(
                Article.category == Category.query.filter_by(
                    name=username).first(),
                Article.show)).order_by(Article.timestamp.desc())
    return render_template('blog/index.html', posts=posts)


@blog_bp.route('/about')
def about():
    admin = Admin.query.first()
    return render_template('blog/about.html', admin=admin)


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    username = session.get('username', 'no_exist_user')

    if current_user.is_authenticated:
        posts = Article.query.with_parent(category).order_by(
            Article.timestamp.desc())
    else:
        posts = Article.query.filter(
            or_(
                Article.category == Category.query.filter_by(
                    name=username).first(),
                Article.show)).with_parent(category).order_by(
                    Article.timestamp.desc())
    if not posts.first():
        abort(404)
    return render_template('blog/category.html',
                           category=category,
                           posts=posts)


def sub_code(matchobj):
    language = matchobj.group(1).replace('\n', '')
    code = matchobj.group(2)
    try:
        lexers = get_lexer_by_name(language)
    except pygments.util.ClassNotFound:
        lexers = guess_lexer(code)
    return highlight(code, lexers, HtmlFormatter())


# 只读状态展示 blog
@blog_bp.route('/articles/<int:post_id>', methods=['GET'])
def show_article(post_id):
    post = Article.query.get_or_404(post_id)
    # print(post_id)
    username = session.get('username', 'no_exist_user')
    if not post.show and (not current_user.is_authenticated
                          and post.category.name != username):  # noqa
        abort(404)

    if not post.body:
        # print(post.body)
        return render_template('blog/article.html', post=post)
        # abort(404)
    # print(post.body)
    code_s = re.sub(r'```\s*(\w+(?:\n))(.*?)```',
                    sub_code,
                    post.body,
                    flags=re.DOTALL)
    body = markdown.markdown(code_s, extensions=['tables'])
    post.body = body

    return render_template('blog/article.html', post=post)

Tblog/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport" />
    <title>{%block title%} {%endblock title%}-{{ admin.blog_title|default('Blog Title',None) }}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <script src={{url_for('static',filename='js/polyfill.min.js')}}></script>
    <script id="MathJax-script" async src={{url_for('static',filename='js/tex-mml-chtml.js')}}></script>
    <script>

        MathJax = {
            tex: {
                inlineMath: [['$', '$'], ['\\(', '\\)']]
            },
            svg: {
                scale: 1,                      // global scaling factor for all expressions
                minScale: .5,                  // smallest scaling factor to use
                matchFontHeight: true,         // true to match ex-height of surrounding font
                mtextInheritFont: false,       // true to make mtext elements use surrounding font
                merrorInheritFont: true,       // true to make merror text use surrounding font
                mathmlSpacing: false,          // true for MathML spacing rules, false for TeX rules
                skipAttributes: {},            // RFDa and other attributes NOT to copy to the output
                exFactor: .5,                  // default size of ex in em units
                displayAlign: 'center',        // default for indentalign when set to 'auto'
                displayIndent: '0',            // default for indentshift when set to 'auto'
                fontCache: 'global',            // or 'global' or 'none'
                localID: null,                 // ID to use for local font cache (for single equation processing)
                internalSpeechTitles: true,    // insert <title> tags with speech content
                titleID: 0                     // initial id number to use for aria-labeledby titles
            }
        };
    </script>

    {% endblock head %}
</head>

<body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="contatiner">
            <div class="navbar-header" style="margin-left: auto;">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"
                    href="{{ url_for('blog.index') }}">{{ admin.blog_title|default('Blog Title',None) }}</a>

            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right" style="margin-right:auto; align-self: auto;;">
                    <li id="home"><a href="{{url_for('blog.index')}}">Home</a></li>
                    <li id="about"><a href="{{url_for('blog.about')}}">About Me</a></li>
                    {% if current_user.is_authenticated %}
                    <li class="dropdown">
                        <a href="{{url_for('admin.mange')}}" class="dropdown-toggle" data-toggle="dropdown"
                            role="button" aria-haspopup="true" aria-expanded="false">Mange <span
                                class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url_for('admin.mange')}}">Manger</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{url_for('admin.get_auth_token')}}">Token</a></li>
                            <li><a href="{{url_for('admin.settings')}}">Settings</a></li>
                            <li><a href="{{url_for('admin.reset_password')}}">Reset Password</a></li>
                        </ul>
                    </li>
                    </li>
                    <li id="logout"><a href="{{url_for('auth.logout',next=request.full_path)}}">Log Out</a></li>
                    {% else %}
                    <li id="login"><a href="{{ url_for('auth.login', next=request.full_path) }}">Log In</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block sidebar %} {% endblock sidebar %}

    <main class="container ">
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock content %}
        {% block footer %} {% endblock footer %}
    </main>
    {% block scripts %}
    <script src={{url_for('static',filename='js/jquery.min.js')}}></script>
    <script src={{url_for('static',filename='js/bootstrap.min.js')}}></script>

    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src={{url_for('static',filename='js/base.js')}}></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-116710997-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-116710997-2');
    </script>


    {% endblock %}
</body>

</html>