Tblog/blueprints/admin.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_required, current_user
from Tblog.extensions import db
from Tblog.models import Admin, Article
from Tblog.utils import redirect_back
from Tblog.forms import SettingForm, SignInForm

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/articles/show', methods=['GET', 'POST'])
@login_required
def switch_show_state():
    aid = request.form.get('aid')

    article = Article.query.get(aid)
    article.show = not article.show
    db.session.add(article)
    db.session.commit()
    return redirect_back()


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about

    return render_template('admin/settings.html', form=form)


@admin_bp.route('/reset_password', methods=['GET', 'POST'])
@login_required
def reset_password():
    form = SignInForm()
    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        db.session.commit()
        flash('Password  updated.', 'success')
        return redirect(url_for('blog.index'))
    return render_template('admin/reset_password.html', form=form)


@admin_bp.route('/token', methods=['GET', 'POST'])
@login_required
def get_auth_token():
    admin = Admin.query.first()
    if request.form.get('reset'):
        admin.set_api_key()
        flash("Reset token success!", "info")
    token = admin.api_key
    return render_template('admin/token.html', token=token)


@admin_bp.route('/mange', methods=['GET', 'POST'])
@login_required
def mange():
    settings_form = SettingForm()
    reset_password_form = SignInForm()
    if settings_form.validate_on_submit():
        return settings()
    if reset_password_form.validate_on_submit():
        return reset_password()
    admin = Admin.query.first()
    if request.form.get('reset'):
        admin.set_api_key()
        flash("Reset token success!", "info")
    token = admin.api_key

    settings_form.name.data = current_user.name
    settings_form.blog_title.data = current_user.blog_title
    settings_form.blog_sub_title.data = current_user.blog_sub_title
    settings_form.about.data = current_user.about

    return render_template('admin/mange.html',
                           token=token,
                           settings_form=settings_form,
                           reset_password_form=reset_password_form)

Tblog/blueprints/blog.py
from flask import session, render_template, Blueprint, abort
from flask_login import current_user
from sqlalchemy import or_
from Tblog.models import Article, Category, Admin
import markdown
import pygments
from pygments import highlight
from pygments.lexers import get_lexer_by_name, guess_lexer
from pygments.formatters import HtmlFormatter
import re
# import markdown
blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/articles')
@blog_bp.route('/')
def index():
    username = session.get('username', 'no_exist_user')
    if current_user.is_authenticated:
        posts = Article.query.order_by(Article.timestamp.desc())
    else:

        posts = Article.query.filter(
            or_(
                Article.category == Category.query.filter_by(
                    name=username).first(),
                Article.show)).order_by(Article.timestamp.desc())
    return render_template('blog/index.html', posts=posts)


@blog_bp.route('/about')
def about():
    admin = Admin.query.first()
    return render_template('blog/about.html', admin=admin)


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    username = session.get('username', 'no_exist_user')

    if current_user.is_authenticated:
        posts = Article.query.with_parent(category).order_by(
            Article.timestamp.desc())
    else:
        posts = Article.query.filter(
            or_(
                Article.category == Category.query.filter_by(
                    name=username).first(),
                Article.show)).with_parent(category).order_by(
                    Article.timestamp.desc())
    if not posts.first():
        abort(404)
    return render_template('blog/category.html',
                           category=category,
                           posts=posts)


def sub_code(matchobj):
    language = matchobj.group(1).replace('\n', '')
    code = matchobj.group(2)
    try:
        lexers = get_lexer_by_name(language)
    except pygments.util.ClassNotFound:
        lexers = guess_lexer(code)
    return highlight(code, lexers, HtmlFormatter())


# 只读状态展示 blog
@blog_bp.route('/articles/<int:post_id>', methods=['GET'])
def show_article(post_id):
    post = Article.query.get_or_404(post_id)
    # print(post_id)
    username = session.get('username', 'no_exist_user')
    if not post.show and (not current_user.is_authenticated
                          and post.category.name != username):  # noqa
        abort(404)

    if not post.body:
        # print(post.body)
        return render_template('blog/article.html', post=post)
        # abort(404)
    # print(post.body)
    code_s = re.sub(r'```\s*(\w+(?:\n))(.*?)```',
                    sub_code,
                    post.body,
                    flags=re.DOTALL)
    body = markdown.markdown(code_s, extensions=['tables'])
    post.body = body

    return render_template('blog/article.html', post=post)

Tblog/templates/blog/_category.html
{% if posts %}
{% for post in posts %}
<h3 class="text-primary"><a href="{{ url_for('.show_article', post_id=post.id) }}">{{ post.title }}</a></h3>
<small>
    Category: <a href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
    &nbsp;&nbsp;
    <span class="float-right" display=>{{ moment(post.timestamp).format('LL') }}</span>
</small>
{% if not loop.last %}
<hr>
{% endif %}
{% endfor %}
{% else %}
<div class="tip">
    <h5>No posts yet.</h5>
</div>
{% endif %}

Tblog/templates/blog/_posts.html
{% if posts.first() %}
{% for post in posts %}
<h3 class="text-primary"><a href="{{ url_for('.show_article', post_id=post.id) }}">{{ post.title }}</a></h3>
<small>
    Category: <a href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
    &nbsp;&nbsp;
    <span class="float-right" display=>{{ moment(post.timestamp).format('LL') }}</span>
</small>
{% if not loop.last %}
<hr>
{% endif %}
{% endfor %}
{% else %}
<div class="tip">
    <h5>No posts yet.</h5>
</div>
{% endif %}

Tblog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About Me{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="page-header">
    <h1>{{admin.username}}</h1>
    <div align='right'>
      <h3 class="text"><em>{{admin.blog_sub_title}}</em></h3>
    </div>

  </div>
  <div id="content"></div>

  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script>
    document.getElementById('content').innerHTML = marked(`{{admin.about|safe}}`);
  </script>
</div>
{% endblock %}

Tblog/templates/blog/article.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="page-header">
    <h1>{{ post.title|safe }}</h1>
    <div align="right">
        <small>
            <form action="{{url_for('admin.switch_show_state')}}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <input type="hidden" name="aid" value="{{post.id}}" />

                <table border="0">
                    {% if current_user.is_authenticated %}
                    <tr>
                        <td> Article State:</td>
                        <td> <a
                                class="label label-{{'success' if post.show else 'default'}}">{{'Public' if post.show else 'Private'}}</a>
                        </td>
                        <td align="right">
                            <input class="btn btn-xs" type="submit" value="change" />
                        </td>

                    </tr>
                    {% endif %}
                    <tr>
                        <td>Category: </td>

                        <td align="right"><a class=""
                                href="{{ url_for('blog.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                        <td align="right">
                            <span display=>{{ moment(post.timestamp).format('LL') }}</span>
                        </td>
                    </tr>
                </table>
            </form>


        </small>
    </div>
</div>

<div id="content">{{ post.body |safe}}</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src={{url_for('static',filename='js/articles.js')}}></script>
{% endblock %}

Tblog/templates/blog/category.html
{% extends 'base.html' %}
{% block title %}Category: {{category.name}}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-8">
        <div class="page-header">
        <h2>Category: {{category.name}}</h2>
        </div>
        {% include 'blog/_category.html' %}
    </div>
</div>

{% endblock %}

Tblog/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="col-sm-8">
        {% include 'blog/_posts.html' %}
    </div>
</div>
{% endblock %}